'use strict'

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_ERROR = 'SIGNUP_ERROR'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const USER_REQUEST = 'USER_REQUEST'
export const USER_SUCCESS = 'USER_SUCCESS'
export const USER_ERROR = 'USER_ERROR'

export const ADD_SUMMONER_REQUEST = 'ADD_SUMMONER_REQUEST'
export const ADD_SUMMONER_SUCCESS = 'ADD_SUMMONER_SUCCESS'
export const ADD_SUMMONER_ERROR = 'ADD_SUMMONER_ERROR'

export const EDIT_USER_REQUEST = 'EDIT_USER_REQUEST'
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS'
export const EDIT_USER_ERROR = 'EDIT_USER_ERROR'

export const RANKINGS_REQUEST = 'RANKINGS_REQUEST'
export const RANKINGS_SUCCESS = 'RANKINGS_SUCCESS'
export const RANKINGS_ERROR = 'RANKINGS_ERROR'
