'use strict'

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_ERROR = 'SIGNUP_ERROR'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const ACCOUNT_REQUEST = 'ACCOUNT_REQUEST'
export const ACCOUNT_SUCCESS = 'ACCOUNT_SUCCESS'
export const ACCOUNT_ERROR = 'ACCOUNT_ERROR'

export const PROFILE_REQUEST = 'PROFILE_REQUEST'
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS'
export const PROFILE_ERROR = 'PROFILE_ERROR'

export const ADD_SUMMONER_REQUEST = 'ADD_SUMMONER_REQUEST'
export const ADD_SUMMONER_SUCCESS = 'ADD_SUMMONER_SUCCESS'
export const ADD_SUMMONER_ERROR = 'ADD_SUMMONER_ERROR'

export const CONFIRM_SUMMONER_REQUEST = 'CONFIRM_SUMMONER_REQUEST'
export const CONFIRM_SUMMONER_SUCCESS = 'CONFIRM_SUMMONER_SUCCESS'
export const CONFIRM_SUMMONER_ERROR = 'CONFIRM_SUMMONER_ERROR'

export const EDIT_USER_REQUEST = 'EDIT_USER_REQUEST'
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS'
export const EDIT_USER_ERROR = 'EDIT_USER_ERROR'

export const RANKINGS_REQUEST = 'RANKINGS_REQUEST'
export const RANKINGS_SUCCESS = 'RANKINGS_SUCCESS'
export const RANKINGS_ERROR = 'RANKINGS_ERROR'

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR'

export const SELECT_SUMMONER_REQUEST = 'SELECT_SUMMONER_REQUEST'
export const SELECT_SUMMONER_SUCCESS = 'SELECT_SUMMONER_SUCCESS'
export const SELECT_SUMMONER_ERROR = 'SELECT_SUMMONER_ERROR'
