export { default as FacebookIcon } from './facebook-icon'
export { default as TwitterIcon } from './twitter-icon'
export { default as InstagramIcon } from './instagram-icon'
export { default as GithubIcon } from './github-icon'
export { default as SpinnerIcon } from './spinner-icon'
export { default as LogoutIcon } from './logout-icon'
export { default as SettingsIcon } from './settings-icon'
